#!/bin/bash
echo "test 5 params:";
ARG="5 4 3 2 1"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="3  5  1  2  4"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  2  4  5  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  2  4  3  5"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="4  5  2  1  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="4  2  3  1  5"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="4  2  1  5  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="2  4  3  1  5"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="5  2  4  3  1"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  4  5  3  2"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="3  4  5  1  2"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="3  1  2  4  5"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="4  2  1  3  5"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="5  2  1  3  4"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  3  4  2  5"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="4  2  1  5  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="2  5  4  3  1"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="4  2  3  5  1"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  5  2  4  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="2  3  5  4  1"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="3  2  5  1  4"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="5  4  2  1  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  5  2  4  3"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  5  3  4  2"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;
ARG="1  3  5  4  2"; ./push_swap $ARG | ./checker $ARG; ./push_swap $ARG | wc -l;